In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('insurance_cleaned.csv')

In [3]:
df.sample(5)

,income_lpa,occupation,insurance_premium_category,age_group,bmi,lifestyle_risk,city_tier
2069,3.04,Software Engineer,Medium,Middle Age,27.727478,high,2
592,24.99,HR Manager,High,Middle Age,23.735308,medium,1
760,29.80,Retail Manager,Medium,Senior,19.019442,low,2
475,18.54,Nurse,Medium,Senior,16.906171,medium,2
2989,38.64,Carpenter,High,Senior,30.119402,high,2

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = df.drop(labels = ['insurance_premium_category'], axis = 1)

In [6]:
X.head()

,income_lpa,occupation,age_group,bmi,lifestyle_risk,city_tier
0,29.90,Factory Worker,Senior,18.401343,medium,2
1,19.22,Businessman,Senior,31.887755,high,3
2,36.95,Sales Manager,Middle Age,27.458654,medium,3
3,14.75,Banker,Middle Age,27.815882,medium,2
4,19.32,Marketing Manager,Middle Age,12.749566,high,2

In [7]:
y = df['insurance_premium_category']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
X_train.shape, X_test.shape

((3200, 6), (800, 6))

In [10]:
y_train.shape, y_test.shape

((3200,), (800,))

In [ ]:
categorical_columns = [